language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
install:
  - "pip install pytest"
  - "cd src/cobwebs; pip install -r requirements.txt; pip install .; cd -"
  - "cd src/dbdriver; pip install -r requirements.txt; pip install .; cd -"
  - "cd src/apiviewer; pip install -r requirements.txt; pip install .; cd -"
  - "cd src/spider; pip install -r requirements.txt; pip install .; cd -"
# command to run tests
script: py.test
